source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '9.0'

target 'swift_test' do
  
pod 'Alamofire', '~> 4.4'
pod 'SwiftyJSON'
pod 'SnapKit', '~> 3.2.0'

  target 'swift_testTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'swift_testUITests' do
    inherit! :search_paths
    # Pods for te
 end

end
